databases:
  - name: ZENSHO_DB
    databaseName: zensho_db_84sb
    user: ZENSHO
    region: singapore

services:
  - type: web
    name: ZENSHO
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ZENSHO_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

